
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: adv-analytics-build
  namespace: adv-analytics
spec:
  output:
    to:
      kind: ImageStreamTag
      name: adv-analytics:latest
  source:
    type: Git
    git: 
      uri: "https://github.com/cnuland/adv-analytics"
      ref: "main"
    contextDir: "app/"
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-python:latest
    type: Docker
  postCommit: {}
  triggers:
  - type: ConfigChange
