apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-analytics
  namespace: adv-analytics
  labels:
    app: adv-analytics
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"adv-analytics:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"adv-analytics\")].image"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adv-analytics
  template:
    metadata:
      labels:
        app: adv-analytics
    spec:
      containers:
      - name: adv-analytics
        image: image-registry.openshift-image-registry.svc:5000/adv-analytics/adv-analytics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
      serviceAccount: adv-analytics
      serviceAccountName: adv-analytics
