kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adv-analytics-binding
roleRef:
  kind: ClusterRole
  name: adv-analytics-view
subjects:
- kind: ServiceAccount
  name: adv-analytics
  namespace: adv-analytics
