apiVersion: v1
kind: Service
metadata:
  name: adv-analytics
  namespace: adv-analytics
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: adv-analytics
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

