apiVersion: v1
kind: Service
metadata:
  name: migration-charts
  namespace: migration-charts
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: migration-charts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

