apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-charts
  labels:
    app: migration-charts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-charts
  template:
    metadata:
      labels:
        app: migration-charts
    spec:
      containers:
      - name: migration-charts
        image: image-registry.openshift-image-registry.svc:5000/migration-charts/migration-charts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
      serviceAccount: charts
      serviceAccountName: charts
