apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8-python
  namespace: migration-charts
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/python-36:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
