apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-chart-view
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
