apiVersion: v1
kind: Service
metadata:
  name: migration-charts
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    deployment: migration-charts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

